### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by vivian-farrell**
Resolved a few code and documentation issues encountered:
Added CORS support for development mode to API
Added missing method-override npm package
Updated Readme

### CODE REVIEW

**Comment by whatSocks** [comment]
@jexp can you give me write access to this repo?

**Comment by cheerfulstoic** [comment]
Is this a node.js repo?  The repo isn't named well if so.  Is it different than neo4j-examples/movies-javascript-node-neo4j?

**Comment by whatSocks** [comment]
@cheerfulstoic based on the name it looks like someone wanted to migrate this repo into the better-named repo.

**Comment by whatSocks** [comment]
@vivian-farrell hey, now that this project is being revived, could you rebase your branch?

**Comment by jexp** [comment]
@whatSocks can you look at the changes in this PR and which of them make sense adding to the project now? Otherwise please close the PR.

**Comment by whatSocks** [comment]
out of date

**Pull request closed without merging**
