### PR TITLE
add pdf note on running in Windows dev environment

### PR DESCRIPTION
**Pull request by c-w-m**
fix lint warnings
update link to Neo4j 3.1.0 (and link text)
update link to original github project

### CODE REVIEW

**Comment by c-w-m** [comment]
lint warnings were primarily:
1. replace " with '
2. add missing ;
3. update neo4j version from 3.0 to 3.1
4. add link to project

**Comment by jexp** [comment]
Hi @c-w-m 
the linter update looks good.

But I don't understand the PDF?
Why not update the docs in the adoc file?
The PDF is a binary which is not editable/diffable etc.
Please update / add to the adoc file instead.

**Comment by c-w-m** [comment]
My bad, I had my notes in Word, hence the pdf format.  I would be happy to do a 'light' edit of the adoc instead.

**Comment by whatSocks** [comment]
feel free to edit the readme, add a new adoc, or edit existing adoc :)

**Comment by c-w-m** [comment]
Can we split this work into a future commit?

**Comment by whatSocks** [comment]
i'm fine with that

**Comment by c-w-m** [comment]
1. light edit on README 
2. removed pdf

cheers

**Pull request merged**
